services:
  fmn-db:
    image: postgres:18
    container_name: fmn-db
    ports:
      - 5432:5432
    volumes:
      - ./db-data/:/var/lib/postgresql
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
